### ISSUE TITLE
module 'colors' not found

### ISSUE THREAD

**Issue by atlemagnussen** [nxvu699134/vn-night.nvim#1]
Hi,

I tried enabling the theme for galaxy line 
```lua
require('vn-night.galaxyline')
```

both galaxyline and the theme is loaded before this and those work fine.

I get this error message when opening neovim

```
E5113: Error while calling lua chunk: ...k/packer/start/vn-night.nvim/lua/vn-night/galaxyline.lua:7: module 'colors' not found:
        no field package.preload['colors']
```

**Comment by nxvu699134** [comment]
Thanks bro. Fixed. Just update with your plug-in manager
